- hosts: all
  gather_facts: no
  name: Enable password authentication.
  tasks:
  - name: Enable password authentication (less secure but simpler for lab).
    become: yes
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: PasswordAuthentication no
      line: PasswordAuthentication yes

  - name: Restart ssh.service.
    become: yes
    systemd:
      name: ssh.service
      state: restarted
